// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZLzFXweHhgoWb10idNrsq54s43mCoi_8',
    appId: '1:849159457463:web:490b9169a9ef46d8c8db32',
    messagingSenderId: '849159457463',
    projectId: 'rakwa-6fafc',
    authDomain: 'rakwa-6fafc.firebaseapp.com',
    storageBucket: 'rakwa-6fafc.appspot.com',
    measurementId: 'G-FL67C9G5MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '1:849159457463:ios:5084f75a5c94c2c6c8db32',
    appId: '1:849159457463:android:cd48542dc12026fdc8db32',
    messagingSenderId: '849159457463',
    projectId: 'rakwa-6fafc',
    storageBucket: 'rakwa-6fafc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtqCoO0NedlmsnEab8acG2CUIaH3XK9ps',
    appId: '1:849159457463:ios:5084f75a5c94c2c6c8db32',
    messagingSenderId: '849159457463',
    projectId: 'rakwa-6fafc',
    storageBucket: 'rakwa-6fafc.appspot.com',
    iosClientId: '849159457463-pspraodcgua3in5i1tvoietf4uaa6g5g.apps.googleusercontent.com',
    iosBundleId: 'com.turkey.rakwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtqCoO0NedlmsnEab8acG2CUIaH3XK9ps',
    appId: '1:849159457463:ios:d9b08a402d50a0f8c8db32',
    messagingSenderId: '849159457463',
    projectId: 'rakwa-6fafc',
    storageBucket: 'rakwa-6fafc.appspot.com',
    iosClientId: '849159457463-0j8tnj3etulqp9rl0um6t3ke9q41fbem.apps.googleusercontent.com',
    iosBundleId: 'rakwa.turkey.com',
  );
}
